### ISSUE TITLE
Watched status in next-episode Android app is not updated automatically by Kodi

### ISSUE THREAD

**Issue by robinsmidsrod** [santah/next-episode-kodi#1]
I've used the next-episode Kodi plugin from the official repos to update watched/unwatched status automatically, but recently (December 2017) it has stopped working. I don't have a lot to go on, but it seems like the JSON-RPC response is not as expected, so there might be a server error causing the error.

A debug log from Kodi has been attached. I'm running Kodi on LibreELEC 8.0.2.

[next-episode-kodi-plugin-issue.log](https://github.com/santah/next-episode-kodi/files/1595241/next-episode-kodi-plugin-issue.log)

**Comment by romanvm** [comment]
Should be fixed by now.

**Comment by robinsmidsrod** [comment]
@romanvm Thank you! I can confirm that the Kodi plugin successfully marked a TV episode as watched in next-episode yesterday evening. Keep up the good work!
